"""add missing crm tables

Revision ID: f8ab85f63219
Revises: 004_asset_hash_keys
Create Date: 2026-02-10 11:08:47.442010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f8ab85f63219'
down_revision: Union[str, Sequence[str], None] = '004_asset_hash_keys'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create missing CRM tables. This migration intentionally does *not* attempt
    # to retrofit existing tables/indexes; it only creates tables that were
    # missing from the earlier schema revisions.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("slot_duration", sa.Integer(), nullable=False),
        sa.Column("buffer_before", sa.Integer(), nullable=False),
        sa.Column("buffer_after", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("ghl_id", sa.String(length=100), nullable=True),
        sa.Column("ghl_location_id", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_calendar_ghl_id"), "calendar", ["ghl_id"], unique=False)
    op.create_index(op.f("ix_calendar_location_id"), "calendar", ["location_id"], unique=False)

    op.create_table(
        "campaign",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("ghl_id", sa.String(length=100), nullable=True),
        sa.Column("ghl_location_id", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaign_ghl_id"), "campaign", ["ghl_id"], unique=False)
    op.create_index(op.f("ix_campaign_location_id"), "campaign", ["location_id"], unique=False)

    op.create_table(
        "form",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("ghl_id", sa.String(length=100), nullable=True),
        sa.Column("ghl_location_id", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_form_ghl_id"), "form", ["ghl_id"], unique=False)
    op.create_index(op.f("ix_form_location_id"), "form", ["location_id"], unique=False)

    op.create_table(
        "funnel",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("ghl_id", sa.String(length=100), nullable=True),
        sa.Column("ghl_location_id", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_funnel_ghl_id"), "funnel", ["ghl_id"], unique=False)
    op.create_index(op.f("ix_funnel_location_id"), "funnel", ["location_id"], unique=False)

    op.create_table(
        "survey",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("ghl_id", sa.String(length=100), nullable=True),
        sa.Column("ghl_location_id", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_survey_ghl_id"), "survey", ["ghl_id"], unique=False)
    op.create_index(op.f("ix_survey_location_id"), "survey", ["location_id"], unique=False)

    op.create_table(
        "appointment",
        sa.Column("calendar_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("ghl_id", sa.String(length=100), nullable=True),
        sa.Column("ghl_location_id", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendar.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_appointment_calendar_id"), "appointment", ["calendar_id"], unique=False)
    op.create_index("ix_appointment_calendar_time", "appointment", ["calendar_id", "start_time"], unique=False)
    op.create_index(op.f("ix_appointment_ghl_id"), "appointment", ["ghl_id"], unique=False)
    op.create_index(op.f("ix_appointment_location_id"), "appointment", ["location_id"], unique=False)

    op.create_table(
        "availability_window",
        sa.Column("calendar_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendar.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("calendar_id", "day_of_week", "start_time", name="uq_availability_window"),
    )
    op.create_index(op.f("ix_availability_window_calendar_id"), "availability_window", ["calendar_id"], unique=False)

    op.create_table(
        "campaign_enrollment",
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "contact_id", name="uq_campaign_enrollment"),
    )
    op.create_index(op.f("ix_campaign_enrollment_campaign_id"), "campaign_enrollment", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_campaign_enrollment_contact_id"), "campaign_enrollment", ["contact_id"], unique=False)
    op.create_index(op.f("ix_campaign_enrollment_location_id"), "campaign_enrollment", ["location_id"], unique=False)

    op.create_table(
        "campaign_step",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("step_type", sa.String(length=20), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("delay_minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaign_step_campaign_id"), "campaign_step", ["campaign_id"], unique=False)

    op.create_table(
        "conversation",
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unread_count", sa.Integer(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("ghl_id", sa.String(length=100), nullable=True),
        sa.Column("ghl_location_id", sa.String(length=100), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversation_contact_id"), "conversation", ["contact_id"], unique=False)
    op.create_index(op.f("ix_conversation_ghl_id"), "conversation", ["ghl_id"], unique=False)
    op.create_index("ix_conversation_location_contact", "conversation", ["location_id", "contact_id"], unique=False)
    op.create_index(op.f("ix_conversation_location_id"), "conversation", ["location_id"], unique=False)

    op.create_table(
        "form_field",
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("field_type", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("options_json", sa.JSON(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("placeholder", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["form_id"], ["form.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_form_field_form_id"), "form_field", ["form_id"], unique=False)

    op.create_table(
        "form_submission",
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("data_json", sa.JSON(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["form_id"], ["form.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_form_submission_form_id"), "form_submission", ["form_id"], unique=False)
    op.create_index(op.f("ix_form_submission_location_id"), "form_submission", ["location_id"], unique=False)

    op.create_table(
        "funnel_page",
        sa.Column("funnel_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url_slug", sa.String(length=100), nullable=False),
        sa.Column("content_html", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("ghl_id", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["funnel_id"], ["funnel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("funnel_id", "url_slug", name="uq_funnel_page_slug"),
    )
    op.create_index(op.f("ix_funnel_page_funnel_id"), "funnel_page", ["funnel_id"], unique=False)

    op.create_table(
        "survey_question",
        sa.Column("survey_id", sa.Uuid(), nullable=False),
        sa.Column("question_text", sa.String(length=500), nullable=False),
        sa.Column("question_type", sa.String(length=20), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("options_json", sa.JSON(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["survey_id"], ["survey.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_survey_question_survey_id"), "survey_question", ["survey_id"], unique=False)

    op.create_table(
        "survey_submission",
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("survey_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("answers_json", sa.JSON(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["survey_id"], ["survey.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_survey_submission_location_id"), "survey_submission", ["location_id"], unique=False)
    op.create_index(op.f("ix_survey_submission_survey_id"), "survey_submission", ["survey_id"], unique=False)

    op.create_table(
        "message",
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("subject", sa.String(length=255), nullable=True),
        sa.Column("from_address", sa.String(length=255), nullable=True),
        sa.Column("to_address", sa.String(length=255), nullable=True),
        sa.Column("provider_id", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_detail", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversation.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_message_conversation", "message", ["conversation_id", "created_at"], unique=False)
    op.create_index(op.f("ix_message_location_id"), "message", ["location_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Only drop tables created in upgrade().
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_location_id"), table_name="message")
    op.drop_index("ix_message_conversation", table_name="message")
    op.drop_table("message")

    op.drop_index(op.f("ix_survey_submission_survey_id"), table_name="survey_submission")
    op.drop_index(op.f("ix_survey_submission_location_id"), table_name="survey_submission")
    op.drop_table("survey_submission")

    op.drop_index(op.f("ix_survey_question_survey_id"), table_name="survey_question")
    op.drop_table("survey_question")

    op.drop_index(op.f("ix_funnel_page_funnel_id"), table_name="funnel_page")
    op.drop_table("funnel_page")

    op.drop_index(op.f("ix_form_submission_location_id"), table_name="form_submission")
    op.drop_index(op.f("ix_form_submission_form_id"), table_name="form_submission")
    op.drop_table("form_submission")

    op.drop_index(op.f("ix_form_field_form_id"), table_name="form_field")
    op.drop_table("form_field")

    op.drop_index(op.f("ix_conversation_location_id"), table_name="conversation")
    op.drop_index("ix_conversation_location_contact", table_name="conversation")
    op.drop_index(op.f("ix_conversation_ghl_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_contact_id"), table_name="conversation")
    op.drop_table("conversation")

    op.drop_index(op.f("ix_campaign_step_campaign_id"), table_name="campaign_step")
    op.drop_table("campaign_step")

    op.drop_index(op.f("ix_campaign_enrollment_location_id"), table_name="campaign_enrollment")
    op.drop_index(op.f("ix_campaign_enrollment_contact_id"), table_name="campaign_enrollment")
    op.drop_index(op.f("ix_campaign_enrollment_campaign_id"), table_name="campaign_enrollment")
    op.drop_table("campaign_enrollment")

    op.drop_index(op.f("ix_availability_window_calendar_id"), table_name="availability_window")
    op.drop_table("availability_window")

    op.drop_index(op.f("ix_appointment_location_id"), table_name="appointment")
    op.drop_index(op.f("ix_appointment_ghl_id"), table_name="appointment")
    op.drop_index("ix_appointment_calendar_time", table_name="appointment")
    op.drop_index(op.f("ix_appointment_calendar_id"), table_name="appointment")
    op.drop_table("appointment")

    op.drop_index(op.f("ix_survey_location_id"), table_name="survey")
    op.drop_index(op.f("ix_survey_ghl_id"), table_name="survey")
    op.drop_table("survey")

    op.drop_index(op.f("ix_funnel_location_id"), table_name="funnel")
    op.drop_index(op.f("ix_funnel_ghl_id"), table_name="funnel")
    op.drop_table("funnel")

    op.drop_index(op.f("ix_form_location_id"), table_name="form")
    op.drop_index(op.f("ix_form_ghl_id"), table_name="form")
    op.drop_table("form")

    op.drop_index(op.f("ix_campaign_location_id"), table_name="campaign")
    op.drop_index(op.f("ix_campaign_ghl_id"), table_name="campaign")
    op.drop_table("campaign")

    op.drop_index(op.f("ix_calendar_location_id"), table_name="calendar")
    op.drop_index(op.f("ix_calendar_ghl_id"), table_name="calendar")
    op.drop_table("calendar")
    # ### end Alembic commands ###
